name: Monorepo CI

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  move-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Enable Corepack
        run: corepack enable

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Bootstrap workspace
        env:
          CI: true
          SKIP_APTOS_CHECK: true
        run: ./scripts/setup-local.sh

      - name: Pull Aptos CLI image
        run: docker pull aptoslabs/aptos-cli:latest

      - name: Run Move tests
        run: pnpm move:test

      - name: Upload Move build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: move-build
          path: move/build

  backend-test:
    runs-on: ubuntu-latest
    needs: move-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Enable Corepack
        run: corepack enable

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Bootstrap workspace
        env:
          CI: true
          SKIP_APTOS_CHECK: true
        run: ./scripts/setup-local.sh

      - name: Lint BFF
        run: pnpm --filter @haigo/bff lint

      - name: Build BFF
        run: pnpm --filter @haigo/bff build

      - name: Upload BFF bundle
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bff-dist
          path: apps/bff/dist

  frontend-build:
    runs-on: ubuntu-latest
    needs: move-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Enable Corepack
        run: corepack enable

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Bootstrap workspace
        env:
          CI: true
          SKIP_APTOS_CHECK: true
        run: ./scripts/setup-local.sh

      - name: Lint frontend
        run: pnpm --filter @haigo/web lint

      - name: Build frontend
        run: pnpm --filter @haigo/web build

      - name: Upload Next.js build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: web-next-build
          path: |
            apps/web/.next
            apps/web/package.json
            apps/web/next.config.mjs
